version: '2'
services:
    app-app:
        image: app
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=app-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    app-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: app-cassandra
    app-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=app-cassandra
    app-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: app-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
